#!/usr/bin/perl

use warnings;
use strict;

local $/ = ""; # read files paragraph-wise; see ``perldoc perlvar''

open my $fh, "< /var/lib/pkg/db"
  or die "Couldn't open package database!\n";

while(<$fh>) {
  my ($pkg_name, $pkg_version, @pkg_file) = split /\n/;
  my @missing = grep ! -e "/$_", @pkg_file;
  next if not @missing;

  print map "/$_ $pkg_name\n", @missing;
}         
 
close($fh);

